Func1b: Func1b.cpp
	g++ -o Func1b Func1b.cpp

Func1: Func1.cpp
	g++ -o Func1 Func1.cpp

Variable2: Variable2.cpp
	g++ -o Variable2 Variable2.cpp

Variable1: Variable1.cpp
	g++ -o Variable1 Variable1.cpp
